input {
  file {
    start_position => "beginning"
    path => "/usr/share/logstash/input/error.log"
 }
}
filter {
  mutate {
    add_field => [ "Hello_field", "Hello world" ]
 }
}
output {
  stdout {
  }
  elasticsearch {
    hosts => "http://elasticsearch:9200"
 }
}
