input {
  beats {
    port => 5046
 }
}
filter {
  mutate {
    add_field => [ "Hello_field", "I'm from FileBeat" ]
 }
}
output {
  stdout {
  }
  elasticsearch {
    hosts => "http://elasticsearch:9200"
 }
}
